AWSTemplateFormatVersion: '2010-09-09'
Description: 'Google OAuth Proxy Roles And Policies'

Resources:
  GoogleOauthProxyLoginFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: GoogleOauthProxyLoginFunctionRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - ssm:*
            Resource: "*"
            Effect: Allow
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com

  GoogleOauthProxyCallbackFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: GoogleOauthProxyCallbackFunctionRolePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - ssm:*
            Resource: "*"
            Effect: Allow
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com

  CloudformationGoogleOauthProxyApi:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: CloudformationGoogleOauthProxyApi
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudformation:*
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - lambda:*
            Resource: "*"
          - Effect: Allow
            Action:
            - s3:GetObject
            Resource:
            - arn:aws:s3:::google-oauth-proxy/*
          - Effect: Allow
            Action:
            - apigateway:*
            Resource:
            - "*"
          - Effect: Allow
            Action: iam:PassRole
            Resource:
              Fn::Sub: arn:aws:iam::*:role/${AWS::StackName}*
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com

Outputs:
  GoogleOauthProxyLoginFunctionRoleArn:
    Value:
      Fn::GetAtt:
      - GoogleOauthProxyLoginFunctionRole
      - Arn
    Description: The GoogleOauthProxyLoginFunctionRole Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-GoogleOauthProxyLoginFunctionRoleArn"
  GoogleOauthProxyCallbackFunctionRoleArn:
    Value:
      Fn::GetAtt:
      - GoogleOauthProxyCallbackFunctionRole
      - Arn
    Description: The GoogleOauthProxyCallbackFunctionRole Arn
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-GoogleOauthProxyCallbackFunctionRoleArn"